### ISSUE TITLE
Backend - Add User Login

### ISSUE THREAD

**Issue by cjbaskin123** [GHNGO/demo-web-project#1]

**Comment by LloydZhang97** [comment]
Friendular will need the user to know what schedules to modify/display. The user login does not need to be complicated, just a username that goes to the database. Schedules don't need to be that secure. This task assumes https://github.com/GHNGO/Frienduler/issues/8 is done. While it doesn't depend on the UI, the person working on this should be aware of what UI will be passing over and how.

**Comment by LloydZhang97** [comment]
Job Done.
