### ISSUE TITLE
Frontend - Add "Add friend" Button to Main Table

### ISSUE THREAD

**Issue by LloydZhang97** [GHNGO/demo-web-project#17]
Add the button and text field that allows for user input. Make the page look nice.

**Comment by LloydZhang97** [comment]
Add the events button that leads to the create events page. The url the page should be Frienduler/{userid}/createEvent

**Comment by genevieveleach** [comment]
Added buttons.

**Comment by LloydZhang97** [comment]
Buttons added. Close when done in the future.
