### ISSUE TITLE
Implement Friends List/Groups System

### ISSUE THREAD

**Issue by cjbaskin123** [GHNGO/demo-web-project#4]

**Comment by LloydZhang97** [comment]
Friendular will be able to keep track of friends of a user. We will need to store the friends of each user. This seems to be a database enhancement. This task assumes https://github.com/GHNGO/Frienduler/issues/8 is done.

**Comment by LloydZhang97** [comment]
This task is ambiguous and could be split into frontend and backend. 2 tasks should be created instead.
