### ISSUE TITLE
Backend - Create Database

### ISSUE THREAD

**Issue by LloydZhang97** [GHNGO/demo-web-project#8]
Friendular will need to store all the user's information somewhere. This task involves creating said database with all the needed fields per user. No connections need to be made from the frontend yet, just create the database to store the user. More fields should be added in later tasks. This task should be marked "Very Important".

**Comment by jarodNakamoto** [comment]
so how should we design our database? I think we should use JSON files but I think we should discuss what exactly goes inside said files. Is one JSON per user, one JSON per group, one JSON in general (which I think is a terrible idea), or some combination? How I think we should implement it is have a JSON per user with a list of groups, friends, and their schedule. We could also have a JSON for a group like our college group with a list of users so we could find those users and compare their schedules.

**Comment by cjbaskin123** [comment]
Database has been implemented with the DatabaseInterface class allowing access to the interface
